# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Documents\Projects\EPI\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1029, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logos/Images/heart-monitoring.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setContentsMargins(5, 0, 5, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_18 = QtWidgets.QFrame(self.centralwidget)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_18.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_18.setLineWidth(0)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame = QtWidgets.QFrame(self.frame_18)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(235, 135))
        self.label_2.setStyleSheet("image: url(:/logos/Images/Unillanos.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.gridLayout_6.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_18)
        self.frame_2.setMinimumSize(QtCore.QSize(230, 340))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.minus_1 = QtWidgets.QPushButton(self.frame_2)
        self.minus_1.setMinimumSize(QtCore.QSize(40, 40))
        self.minus_1.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.minus_1.setFont(font)
        self.minus_1.setStyleSheet("QPushButton{\n"
"    color: rgb(247, 247, 247);\n"
"    \n"
"    \n"
"    background-color: rgb(51, 209, 122);\n"
"border-radius: 20%;\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: rgb(230, 97, 0);}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  border: 1.5px solid black;\n"
"}")
        self.minus_1.setCheckable(True)
        self.minus_1.setObjectName("minus_1")
        self.horizontalLayout.addWidget(self.minus_1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_3.addWidget(self.label_19)
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.label_21)
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(154, 153, 150);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_3.addWidget(self.label_20)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.plus_1 = QtWidgets.QPushButton(self.frame_2)
        self.plus_1.setMinimumSize(QtCore.QSize(40, 40))
        self.plus_1.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.plus_1.setFont(font)
        self.plus_1.setStyleSheet("QPushButton{\n"
"    color: rgb(247, 247, 247);\n"
"    \n"
"    \n"
"    background-color: rgb(51, 209, 122);\n"
"border-radius: 20%;\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: rgb(230, 97, 0);}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  border: 1.5px solid black;\n"
"}")
        self.plus_1.setCheckable(True)
        self.plus_1.setObjectName("plus_1")
        self.horizontalLayout.addWidget(self.plus_1)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.minus_2 = QtWidgets.QPushButton(self.frame_2)
        self.minus_2.setMinimumSize(QtCore.QSize(40, 40))
        self.minus_2.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.minus_2.setFont(font)
        self.minus_2.setStyleSheet("QPushButton{\n"
"    color: rgb(247, 247, 247);\n"
"    \n"
"    \n"
"    background-color: rgb(51, 209, 122);\n"
"border-radius: 20%;\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: rgb(230, 97, 0);}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  border: 1.5px solid black;\n"
"}")
        self.minus_2.setCheckable(True)
        self.minus_2.setObjectName("minus_2")
        self.horizontalLayout_4.addWidget(self.minus_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_6.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_6.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(154, 153, 150);")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_6.addWidget(self.label_24)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.plus_2 = QtWidgets.QPushButton(self.frame_2)
        self.plus_2.setMinimumSize(QtCore.QSize(40, 40))
        self.plus_2.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.plus_2.setFont(font)
        self.plus_2.setStyleSheet("QPushButton{\n"
"    color: rgb(247, 247, 247);\n"
"    \n"
"    \n"
"    background-color: rgb(51, 209, 122);\n"
"border-radius: 20%;\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: rgb(230, 97, 0);}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  border: 1.5px solid black;\n"
"}")
        self.plus_2.setCheckable(True)
        self.plus_2.setObjectName("plus_2")
        self.horizontalLayout_4.addWidget(self.plus_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minus_3 = QtWidgets.QPushButton(self.frame_2)
        self.minus_3.setMinimumSize(QtCore.QSize(40, 40))
        self.minus_3.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.minus_3.setFont(font)
        self.minus_3.setStyleSheet("QPushButton{\n"
"    color: rgb(247, 247, 247);\n"
"    \n"
"    \n"
"    background-color: rgb(51, 209, 122);\n"
"border-radius: 20%;\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: rgb(230, 97, 0);}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  border: 1.5px solid black;\n"
"}")
        self.minus_3.setCheckable(True)
        self.minus_3.setObjectName("minus_3")
        self.horizontalLayout_2.addWidget(self.minus_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(154, 153, 150);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.plus_3 = QtWidgets.QPushButton(self.frame_2)
        self.plus_3.setMinimumSize(QtCore.QSize(40, 40))
        self.plus_3.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.plus_3.setFont(font)
        self.plus_3.setStyleSheet("QPushButton{\n"
"    color: rgb(247, 247, 247);\n"
"    \n"
"    \n"
"    background-color: rgb(51, 209, 122);\n"
"border-radius: 20%;\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: rgb(230, 97, 0);}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  border: 1.5px solid black;\n"
"}")
        self.plus_3.setCheckable(True)
        self.plus_3.setObjectName("plus_3")
        self.horizontalLayout_2.addWidget(self.plus_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.gridLayout_6.addWidget(self.frame_2, 2, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_18)
        self.frame_3.setMinimumSize(QtCore.QSize(190, 100))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_25 = QtWidgets.QLabel(self.frame_3)
        self.label_25.setMinimumSize(QtCore.QSize(0, 0))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(154, 153, 150);")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout.addWidget(self.label_25)
        self.enviar_button = QtWidgets.QPushButton(self.frame_3)
        self.enviar_button.setMinimumSize(QtCore.QSize(0, 0))
        self.enviar_button.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.enviar_button.setFont(font)
        self.enviar_button.setStyleSheet("QPushButton{\n"
"    color: rgb(247, 247, 247);\n"
"    background-color: rgb(51, 209, 122);\n"
"    border-radius: 10%;\n"
"    border: 1px solid #000;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {background-color: rgb(230, 97, 0);}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  border: 1.5px solid black;\n"
"}")
        self.enviar_button.setCheckable(True)
        self.enviar_button.setObjectName("enviar_button")
        self.verticalLayout.addWidget(self.enviar_button)
        self.datos_button = QtWidgets.QPushButton(self.frame_3)
        self.datos_button.setMinimumSize(QtCore.QSize(0, 0))
        self.datos_button.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.datos_button.setFont(font)
        self.datos_button.setStyleSheet("QPushButton{\n"
"    color: rgb(247, 247, 247);\n"
"    background-color: rgb(51, 209, 122);\n"
"    border-radius: 10%;\n"
"    border: 1px solid #000;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {background-color: rgb(230, 97, 0);}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  border: 1.5px solid black;\n"
"}")
        self.datos_button.setCheckable(True)
        self.datos_button.setObjectName("datos_button")
        self.verticalLayout.addWidget(self.datos_button)
        self.gridLayout_6.addWidget(self.frame_3, 3, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_18)
        self.label_26.setMinimumSize(QtCore.QSize(0, 20))
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(154, 153, 150);")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_18, 0, 2, 3, 1)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.on = QtWidgets.QPushButton(self.frame_5)
        self.on.setEnabled(True)
        self.on.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.on.setFont(font)
        self.on.setStyleSheet("QPushButton{\n"
"    color: rgb(247, 247, 247);\n"
"    background-color: rgb(230, 97, 0);\n"
"    border-radius: 10%;\n"
"    border: 1px solid #000;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {background-color: rgb(51, 209, 122);}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  border: 1.5px solid black;\n"
"}\n"
"")
        self.on.setCheckable(True)
        self.on.setChecked(False)
        self.on.setObjectName("on")
        self.horizontalLayout_5.addWidget(self.on)
        self.off = QtWidgets.QPushButton(self.frame_5)
        self.off.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.off.setFont(font)
        self.off.setStyleSheet("QPushButton{\n"
"    color: rgb(247, 247, 247);\n"
"    background-color: rgb(230, 97, 0);\n"
"    border-radius: 10%;\n"
"    border: 1px solid #000;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {background-color: rgb(51, 209, 122);}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  border: 1.5px solid black;\n"
"}\n"
"")
        self.off.setCheckable(True)
        self.off.setObjectName("off")
        self.horizontalLayout_5.addWidget(self.off)
        self.systems = QtWidgets.QPushButton(self.frame_5)
        self.systems.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.systems.setFont(font)
        self.systems.setStyleSheet("QPushButton{\n"
"    color: rgb(247, 247, 247);\n"
"    background-color: rgb(230, 97, 0);\n"
"    border-radius: 10%;\n"
"    border: 1px solid #000;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {background-color: rgb(51, 209, 122);}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  border: 1.5px solid black;\n"
"}\n"
"")
        self.systems.setCheckable(True)
        self.systems.setObjectName("systems")
        self.horizontalLayout_5.addWidget(self.systems)
        self.gridLayout_7.addWidget(self.frame_5, 2, 0, 1, 2)
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setMinimumSize(QtCore.QSize(197, 30))
        self.frame_7.setMaximumSize(QtCore.QSize(197, 32))
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setContentsMargins(0, 0, 15, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setMinimumSize(QtCore.QSize(26, 26))
        self.label_9.setMaximumSize(QtCore.QSize(26, 26))
        self.label_9.setStyleSheet("border-image: url(:/logos/Images/full-battery.jpg);")
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setMinimumSize(QtCore.QSize(26, 26))
        self.label_12.setMaximumSize(QtCore.QSize(26, 26))
        self.label_12.setStyleSheet("border-image: url(:/logos/Images/full-battery.jpg);")
        self.label_12.setText("")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setMinimumSize(QtCore.QSize(26, 26))
        self.label_11.setMaximumSize(QtCore.QSize(26, 26))
        self.label_11.setStyleSheet("border-image: url(:/logos/Images/electric.jpg);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.gridLayout_7.addWidget(self.frame_7, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_19 = QtWidgets.QFrame(self.centralwidget)
        self.frame_19.setMaximumSize(QtCore.QSize(195, 120))
        self.frame_19.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(129, 61, 156);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.frame_19.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setLineWidth(-17)
        self.frame_19.setMidLineWidth(-8)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_19)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.Ppeak_label = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.Ppeak_label.setFont(font)
        self.Ppeak_label.setLineWidth(1)
        self.Ppeak_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Ppeak_label.setObjectName("Ppeak_label")
        self.verticalLayout_18.addWidget(self.Ppeak_label)
        self.label_45 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_18.addWidget(self.label_45)
        self.gridLayout_4.addLayout(self.verticalLayout_18, 0, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.label_43, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_19)
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setMaximumSize(QtCore.QSize(195, 120))
        self.frame_15.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(129, 61, 156);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setLineWidth(-17)
        self.frame_15.setMidLineWidth(-8)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_28 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_7.addWidget(self.label_28)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_29 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setLineWidth(1)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_13.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_13.addWidget(self.label_30)
        self.horizontalLayout_7.addLayout(self.verticalLayout_13)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.centralwidget)
        self.frame_16.setMaximumSize(QtCore.QSize(195, 120))
        self.frame_16.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(129, 61, 156);\n"
"color: rgb(255, 255, 255);")
        self.frame_16.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setLineWidth(-17)
        self.frame_16.setMidLineWidth(-8)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_31 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_8.addWidget(self.label_31)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_32 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setLineWidth(1)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_14.addWidget(self.label_32)
        self.label_33 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_14.addWidget(self.label_33)
        self.horizontalLayout_8.addLayout(self.verticalLayout_14)
        self.verticalLayout_2.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.centralwidget)
        self.frame_17.setMaximumSize(QtCore.QSize(195, 120))
        self.frame_17.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(129, 61, 156);\n"
"color: rgb(255, 255, 255);")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setLineWidth(-17)
        self.frame_17.setMidLineWidth(-8)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_34 = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_9.addWidget(self.label_34)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_35 = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setLineWidth(1)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_15.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_15.addWidget(self.label_36)
        self.horizontalLayout_9.addLayout(self.verticalLayout_15)
        self.verticalLayout_2.addWidget(self.frame_17)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_5.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_5.setHorizontalSpacing(0)
        self.gridLayout_5.setVerticalSpacing(10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.graphWidget_3 = PlotWidget(self.frame_6)
        self.graphWidget_3.setObjectName("graphWidget_3")
        self.gridLayout_5.addWidget(self.graphWidget_3, 2, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 160))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frame_8.setFont(font)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_10.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.lb_on_off = QtWidgets.QLabel(self.frame_10)
        self.lb_on_off.setMinimumSize(QtCore.QSize(0, 0))
        self.lb_on_off.setMaximumSize(QtCore.QSize(165, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lb_on_off.setFont(font)
        self.lb_on_off.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_on_off.setObjectName("lb_on_off")
        self.verticalLayout_4.addWidget(self.lb_on_off)
        self.line_5 = QtWidgets.QFrame(self.frame_10)
        self.line_5.setMinimumSize(QtCore.QSize(0, 0))
        self.line_5.setMaximumSize(QtCore.QSize(165, 16777215))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_4.addWidget(self.line_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 4, 1, 1)
        self.img_on_off = QtWidgets.QLabel(self.frame_10)
        self.img_on_off.setMinimumSize(QtCore.QSize(120, 115))
        self.img_on_off.setMaximumSize(QtCore.QSize(120, 115))
        self.img_on_off.setStyleSheet("border-image: url(:/logos/Images/old-man.jpg);")
        self.img_on_off.setText("")
        self.img_on_off.setScaledContents(True)
        self.img_on_off.setObjectName("img_on_off")
        self.gridLayout_2.addWidget(self.img_on_off, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.frame_10, 0, 1, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.frame_9.setFont(font)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 20)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(35)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.play_stop_button = QtWidgets.QPushButton(self.frame_9)
        self.play_stop_button.setEnabled(True)
        self.play_stop_button.setMinimumSize(QtCore.QSize(0, 0))
        self.play_stop_button.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.play_stop_button.setFont(font)
        self.play_stop_button.setStyleSheet("QPushButton{\n"
"    color: rgb(247, 247, 247);\n"
"    \n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 159, 41, 225), stop:1 rgba(248, 54, 0, 255));\n"
"    border-radius: 10%;\n"
"    border: 1px solid #000;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {background-color: rgb(51, 209, 122);}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  border: 1.5px solid black;\n"
"}\n"
"")
        self.play_stop_button.setCheckable(True)
        self.play_stop_button.setChecked(False)
        self.play_stop_button.setObjectName("play_stop_button")
        self.gridLayout_3.addWidget(self.play_stop_button, 1, 0, 1, 1)
        self.lb_on_off_2 = QtWidgets.QLabel(self.frame_9)
        self.lb_on_off_2.setMinimumSize(QtCore.QSize(0, 0))
        self.lb_on_off_2.setMaximumSize(QtCore.QSize(165, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lb_on_off_2.setFont(font)
        self.lb_on_off_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_on_off_2.setWordWrap(True)
        self.lb_on_off_2.setObjectName("lb_on_off_2")
        self.gridLayout_3.addWidget(self.lb_on_off_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_9, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_8, 4, 0, 1, 1)
        self.graphWidget_1 = PlotWidget(self.frame_6)
        self.graphWidget_1.setObjectName("graphWidget_1")
        self.gridLayout_5.addWidget(self.graphWidget_1, 0, 0, 1, 1)
        self.graphWidget_2 = PlotWidget(self.frame_6)
        self.graphWidget_2.setObjectName("graphWidget_2")
        self.gridLayout_5.addWidget(self.graphWidget_2, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_6, 0, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ventilador mecanico"))
        self.minus_1.setText(_translate("MainWindow", "-"))
        self.label_19.setText(_translate("MainWindow", "VOLUMEN"))
        self.label_21.setText(_translate("MainWindow", "340"))
        self.label_20.setText(_translate("MainWindow", "ml"))
        self.plus_1.setText(_translate("MainWindow", "+"))
        self.minus_2.setText(_translate("MainWindow", "-"))
        self.label_22.setText(_translate("MainWindow", "FRECUENCIA"))
        self.label_23.setText(_translate("MainWindow", "21"))
        self.label_24.setText(_translate("MainWindow", "Resp/min"))
        self.plus_2.setText(_translate("MainWindow", "+"))
        self.minus_3.setText(_translate("MainWindow", "-"))
        self.label_14.setText(_translate("MainWindow", "Tiem. Insp"))
        self.label_13.setText(_translate("MainWindow", "21"))
        self.label_4.setText(_translate("MainWindow", "s"))
        self.plus_3.setText(_translate("MainWindow", "+"))
        self.label_25.setText(_translate("MainWindow", "Variables no enviadas"))
        self.enviar_button.setText(_translate("MainWindow", "Enviar parametros"))
        self.datos_button.setText(_translate("MainWindow", "Datos paciente"))
        self.label_26.setText(_translate("MainWindow", "Parametros"))
        self.label.setText(_translate("MainWindow", "Monitoring"))
        self.on.setText(_translate("MainWindow", "ON"))
        self.off.setText(_translate("MainWindow", "OFF"))
        self.systems.setText(_translate("MainWindow", "Variables"))
        self.label_6.setText(_translate("MainWindow", "B1"))
        self.label_8.setText(_translate("MainWindow", "B2"))
        self.label_10.setText(_translate("MainWindow", "AC"))
        self.Ppeak_label.setText(_translate("MainWindow", "28"))
        self.label_45.setText(_translate("MainWindow", "cmH20"))
        self.label_43.setText(_translate("MainWindow", "Ppeak"))
        self.label_28.setText(_translate("MainWindow", "ExpMinVol"))
        self.label_29.setText(_translate("MainWindow", "28"))
        self.label_30.setText(_translate("MainWindow", "l/min"))
        self.label_31.setText(_translate("MainWindow", "VTE"))
        self.label_32.setText(_translate("MainWindow", "28"))
        self.label_33.setText(_translate("MainWindow", "m"))
        self.label_34.setText(_translate("MainWindow", "fTotal"))
        self.label_35.setText(_translate("MainWindow", "28"))
        self.label_36.setText(_translate("MainWindow", "cmH20"))
        self.lb_on_off.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>System: Off</p></body></html>"))
        self.lb_on_off.setText(_translate("MainWindow", "System: Off"))
        self.play_stop_button.setText(_translate("MainWindow", "Stop"))
        self.lb_on_off_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>System: Off</p></body></html>"))
        self.lb_on_off_2.setText(_translate("MainWindow", "Play/Stop graphs"))
from pyqtgraph import PlotWidget
import logos_rc
